'use client'

import { createContext, useContext, useEffect, useMemo, useState } from 'react'

export type Locale = 'en' | 'hi' | 'mr' | 'bn' | 'gu' | 'ta' | 'te' | 'pa' | 'kn' | 'ml' | 'as'

type Copy = Record<string, string>

const base: Copy = { brand: 'KrishiRakshak AI', tag: 'AI crop care', login: 'Sign in', register: 'Create account', phone: 'Mobile number', password: 'Password', name: 'Your name', continue: 'Continue', demoFarmer: 'Continue as Demo Farmer', demoOfficer: 'Continue as Agriculture Officer', farmer: 'Farmer', officer: 'Officer', dashboard: 'Dashboard', farms: 'My farms', scan: 'Scan crop', history: 'Scan history', alerts: 'Alerts', profile: 'Profile', weather: 'Weather & risk', advisory: 'Advisory', overview: 'Overview', map: 'Disease map', reports: 'Reports', validation: 'Validation', analytics: 'Analytics', greeting: 'Namaste, Vijay', protect: 'Detect early. Protect your crop.', scanPrompt: 'AI-powered crop care for smarter, healthier farming.', scanNow: 'Scan your crop', today: 'Today in Nashik', risk: 'Crop risk', attention: 'Needs attention', recent: 'Recent scans', language: 'Language', logout: 'Sign out', analyzing: 'AI is analyzing your crop…', analyze: 'Analyze crop', result: 'Your crop needs attention', symptoms: 'Symptoms detected', recommendations: 'What should you do?', chatbot: 'Ask Krishi AI', chatbotSub: 'Your AI-powered crop care companion', nearby: 'Nearby Help & Stores', upload: 'Upload from Gallery', remove: 'Remove photo', welcome: 'Welcome back!', forgot: 'Forgot password?', create: 'Create Account', back: 'Back to Dashboard', send: 'Send', clear: 'Clear Chat', newChat: 'New Chat', attach: 'Attach Image', voice: 'Voice input', selectLanguage: 'Select Language', edit: 'Edit Profile', save: 'Save changes', farm: 'Farm', location: 'Location', crop: 'Primary Crop', health: 'Crop Health', confidence: 'AI Confidence', scans: 'Total Scans', healthy: 'Healthy Scans', issues: 'Issues Detected' }

const overrides: Partial<Record<Locale, Copy>> = {
  hi: { brand: 'कृषिरक्षक AI', tag: 'एआई फसल देखभाल', login: 'साइन इन', register: 'खाता बनाएं', farmer: 'किसान', officer: 'अधिकारी', dashboard: 'डैशबोर्ड', farms: 'मेरे खेत', scan: 'फसल स्कैन', history: 'स्कैन इतिहास', alerts: 'सूचनाएं', profile: 'प्रोफाइल', greeting: 'नमस्ते, विजय', protect: 'जल्दी पहचानें। फसल बचाएं।', scanNow: 'फसल स्कैन करें', language: 'भाषा', logout: 'साइन आउट', chatbot: 'कृषि एआई सहायक', back: 'डैशबोर्ड पर वापस', selectLanguage: 'भाषा चुनें' },
  mr: { brand: 'कृषिरक्षक AI', tag: 'एआय पीक काळजी', login: 'साइन इन', register: 'खाते तयार करा', farmer: 'शेतकरी', officer: 'अधिकारी', dashboard: 'डॅशबोर्ड', farms: 'माझी शेती', scan: 'पीक स्कॅन', history: 'स्कॅन इतिहास', alerts: 'सूचना', profile: 'प्रोफाइल', greeting: 'नमस्कार, विजय', protect: 'लवकर ओळखा. पीक वाचवा.', scanNow: 'पीक स्कॅन करा', language: 'भाषा', logout: 'साइन आउट', chatbot: 'कृषी एआय सहाय्यक', back: 'डॅशबोर्डवर परत', selectLanguage: 'भाषा निवडा' },
  bn: { brand: 'কৃষিরক্ষক AI', farmer: 'কৃষক', officer: 'কর্মকর্তা', dashboard: 'ড্যাশবোর্ড', scan: 'ফসল স্ক্যান', profile: 'প্রোফাইল', language: 'ভাষা' }, gu: { brand: 'કૃષિરક્ષક AI', farmer: 'ખેડૂત', officer: 'અધિકારી', dashboard: 'ડેશબોર્ડ', scan: 'પાક સ્કેન', profile: 'પ્રોફાઇલ', language: 'ભાષા' }, ta: { brand: 'கிருஷிரக்ஷக் AI', farmer: 'விவசாயி', officer: 'அதிகாரி', dashboard: 'டாஷ்போர்டு', scan: 'பயிர் ஸ்கேன்', profile: 'சுயவிவரம்', language: 'மொழி' }, te: { brand: 'కృషిరక్షక్ AI', farmer: 'రైతు', officer: 'అధికారి', dashboard: 'డాష్‌బోర్డ్', scan: 'పంట స్కాన్', profile: 'ప్రొఫైల్', language: 'భాష' }, pa: { brand: 'ਕ੍ਰਿਸ਼ੀਰਕਸ਼ਕ AI', farmer: 'ਕਿਸਾਨ', officer: 'ਅਧਿਕਾਰੀ', dashboard: 'ਡੈਸ਼ਬੋਰਡ', scan: 'ਫਸਲ ਸਕੈਨ', profile: 'ਪ੍ਰੋਫਾਈਲ', language: 'ਭਾਸ਼ਾ' }, kn: { brand: 'ಕೃಷಿರಕ್ಷಕ AI', farmer: 'ರೈತ', officer: 'ಅಧಿಕಾರಿ', dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', scan: 'ಬೆಳೆ ಸ್ಕ್ಯಾನ್', profile: 'ಪ್ರೊಫೈಲ್', language: 'ಭಾಷೆ' }, ml: { brand: 'കൃഷിരക്ഷക് AI', farmer: 'കർഷകൻ', officer: 'ഉദ്യോഗസ്ഥൻ', dashboard: 'ഡാഷ്ബോർഡ്', scan: 'വിള സ്കാൻ', profile: 'പ്രൊഫൈൽ', language: 'ഭാഷ' }, as: { brand: 'কৃষিৰক্ষক AI', farmer: 'কৃষক', officer: 'বিষয়া', dashboard: 'ডেশ্বব’ৰ্ড', scan: 'শস্য স্কেন', profile: 'প্ৰফাইল', language: 'ভাষা' }
}

export const localeLabels: Record<Locale, string> = { en: 'English', hi: 'हिन्दी', mr: 'मराठी', bn: 'বাংলা', gu: 'ગુજરાતી', ta: 'தமிழ்', te: 'తెలుగు', pa: 'ਪੰਜਾਬੀ', kn: 'ಕನ್ನಡ', ml: 'മലയാളം', as: 'অসমীয়া' }
const translations = Object.fromEntries((Object.keys(localeLabels) as Locale[]).map((locale) => [locale, { ...base, ...(overrides[locale] || {}) }])) as Record<Locale, Copy>

const I18nContext = createContext<{ locale: Locale; setLocale: (locale: Locale) => void; t: (key: string) => string }>({ locale: 'en', setLocale: () => {}, t: (key) => base[key] || key })
export function I18nProvider({ children }: { children: React.ReactNode }) { const [locale, setLocaleState] = useState<Locale>('en'); useEffect(() => { const saved = window.localStorage.getItem('kr-locale') as Locale | null; if (saved && saved in localeLabels) setLocaleState(saved) }, []); const setLocale = (next: Locale) => { setLocaleState(next); window.localStorage.setItem('kr-locale', next) }; const value = useMemo(() => ({ locale, setLocale, t: (key: string) => translations[locale][key] || base[key] || key }), [locale]); return <I18nContext.Provider value={value}>{children}</I18nContext.Provider> }
export const useI18n = () => useContext(I18nContext)
export { translations }
